[package]
name = "client"
version = "1.9.29"
description = "Solana Client"
authors = ["Dean"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-client"
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
bincode = "1.3.3"
bs58 = "0.4.0"
clap = "2.33.0"
indicatif = "0.16.2"
jsonrpc-core = "18.0.0"
log = "0.4.14"
rayon = "1.5.1"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "rustls-tls", "json"] }
semver = "1.0.4"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.72"
account-decoder = { path = "../account-decoder", version = "=1.9.29" }
clap-utils = { path = "../clap-utils", version = "=1.9.29" }
faucet = { path = "../faucet", version = "=1.9.29" }
net-utils = { path = "../net-utils", version = "=1.9.29" }
sdk = { path = "../sdk", version = "=1.9.29" }
transaction-status = { path = "../transaction-status", version = "=1.9.29" }
version = { path = "../version", version = "=0.6.3" }
thiserror = "1.0"
tokio = { version = "~1.14.1", features = ["full"] }
tungstenite = { version = "0.16.0", features = ["rustls-tls-webpki-roots"] }
url = "2.2.2"
evm-state = { path = "../evm-utils/evm-state" }
evm-rpc = { path = "../evm-utils/evm-rpc" }
derivative = "2.2"

[dev-dependencies]
assert_matches = "1.5.0"
jsonrpc-http-server = "18.0.0"
logger = { path = "../logger", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
