[package]
authors = [""]
edition = "2021"
name = "replica-lib"
description = "The library used for replication by both the client and server"
version = "1.9.29"
repository = ""
license = "Apache-2.0"
homepage = ""
documentation = ""

[dependencies]

thiserror = "1.0.40"
crossbeam-channel = "0.5"
futures-util = "0.3"
log = "0.4.11"
prost = "0.11.0"
rpc = { path = "../rpc", version = "=1.9.29" }
runtime = { path = "../runtime", version = "=1.9.29" }
sdk = { path = "../sdk", version = "=1.9.29" }
client = { path = "../client", version = "=1.9.29" }
storage-bigtable = { path = "../storage-bigtable", version = "=1.9.29" }
ledger = { path = "../ledger", version = "=1.9.29" }
clap = "2.33.1"

sha3 = "0.9.1"

rlp = "0.5.0"

tokio = { version = "1.14.1", features = ["full", "time"] }
tonic = { version = "0.8.1", features = ["tls", "transport", "gzip"] }
async-trait = "0.1.64"

# Additional deps for triedb_repl_server
derive_more = "0.99.11"

derivative="2.2"
evm-state = { path = "../evm-utils/evm-state" }
evm-rpc = { path = "../evm-utils/evm-rpc" }
primitive-types = "0.8.0"
rocksdb = { package = "rocksdb", version = "0.20.1", default-features = false }

# triedb = { git = "https://github.com/velas/triedb", tag = "rocksdb-v0.20.1-orth", features = ["rocksdb"] }
triedb = { path = "../triedb", features = ["rocksdb"] }
rangemap = { version = "1.3.0", features = ["serde1"]}

# Additional deps for triedb_repl_client
serde_json = "1.0.82"
serde = "1.0.152"

[dev-dependencies]
assert_matches = "1.5.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.8.0"
