[package]
authors = [""]
edition = "2021"
name = "validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.9.29"
repository = ""
license = "Apache-2.0"
homepage = ""
default-run = "validator"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
console = "0.15.0"
core_affinity = "0.5.10"
fd-lock = "=3.0.6"
indicatif = "0.16.2"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils= "18.0.0"
log = "0.4.14"
num_cpus = "1.13.0"
rand = "0.7.0"
clap-utils = { path = "../clap-utils", version = "=1.9.29" }
cli-config = { path = "../cli-config", version = "=1.9.29" }
client = { path = "../client", version = "=1.9.29" }
core = { path = "../core", version = "=1.9.29" }
download-utils = { path = "../download-utils", version = "=1.9.29" }
entry = { path = "../entry", version = "=1.9.29" }
faucet = { path = "../faucet", version = "=1.9.29" }
genesis-utils = { path = "../genesis-utils", version = "=1.9.29" }
gossip = { path = "../gossip", version = "=1.9.29" }
ledger = { path = "../ledger", version = "=1.9.29" }
logger = { path = "../logger", version = "=1.9.29" }
metrics = { path = "../metrics", version = "=1.9.29" }
net-utils = { path = "../net-utils", version = "=1.9.29" }
perf = { path = "../perf", version = "=1.9.29" }
poh = { path = "../poh", version = "=1.9.29" }
replica-lib = { path = "../replica-lib", version = "=1.9.29" }
rpc = { path = "../rpc", version = "=1.9.29" }
runtime = { path = "../runtime", version = "=1.9.29" }
sdk = { path = "../sdk", version = "=1.9.29" }
send-transaction-service = { path = "../send-transaction-service", version = "=1.9.29" }
streamer = { path = "../streamer", version = "=1.9.29" }
test-validator = { path = "../test-validator", version = "=1.9.29" }
version = { path = "../version", version = "=0.6.3" }
vote-program = { path = "../programs/vote", version = "=1.9.29" }

tokio = { version = "1.14.1", features = ["full"] }
symlink = "0.1.0"

evm-state = { path = "../evm-utils/evm-state" }
tempfile = "3"
[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = {package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"]}

[target."cfg(unix)".dependencies]
libc = "0.2.108"
signal-hook = "0.3.10"
sysctl = "0.4.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
