[package]
name = "solana-streamer"
version = "1.9.29"
description = "Solana Streamer"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-streamer"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
futures-util = "0.3.19"
histogram = "0.6.9"
itertools = "0.10.3"
libc = "0.2.115"
log = "0.4.14"
nix = "0.23.1"
quinn = "0.8.0"
rand = "0.7.0"
rcgen = "0.8.14"
rustls = { version = "0.20.2", features = ["dangerous_configuration"] }
pem = "1.0.2"
pkcs8 = { version = "0.8.0", features = ["alloc"] }
solana-logger = { path = "../logger", version = "=1.9.29" }
solana-metrics = { path = "../metrics", version = "=1.9.29" }
solana-sdk = { path = "../sdk", version = "=1.9.29" }
solana-perf = { path = "../perf", version = "=1.9.29" }
thiserror = "1.0"
tokio = { version = "~1.14.1", features = ["full"] }

[dev-dependencies]

[lib]
crate-type = ["lib"]
name = "solana_streamer"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
