[package]
name = "ledger"
version = "1.9.29"
description = "ledger"
authors = [""]
repository = ""
license = "Apache-2.0"
homepage = ""
documentation = ""
edition = "2021"


[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
chrono = { version = "0.4.11", features = ["serde"] }
chrono-humanize = "0.2.1"
crossbeam-channel = "0.5"
fs_extra = "1.2.0"
futures = "0.3.17"
itertools = "0.10.1"
lazy_static = "1.4.0"
libc = "0.2.108"
log = { version = "0.4.14" }
num_cpus = "1.13.0"
num_enum = "0.5.4"
prost = "0.11.0"
rand = "0.7.0"
rand_chacha = "0.2.2"
rayon = "1.5.1"
serde = "1.0.130"
serde_bytes = "0.11.5"
sha2 = "0.9.8"
#bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.9.29" }
entry = { path = "../entry", version = "=1.9.29" }
frozen-abi = { path = "../frozen-abi", version = "=1.9.29" }
frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.9.29" }
transaction-status = { path = "../transaction-status", version = "=1.9.29" }
logger = { path = "../logger", version = "=1.9.29" }
measure = { path = "../measure", version = "=1.9.29" }
metrics = { path = "../metrics", version = "=1.9.29" }
perf = { path = "../perf", version = "=1.9.29" }
program-runtime = { path = "../program-runtime", version = "=1.9.29" }
rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.9.29" }
runtime = { path = "../runtime", version = "=1.9.29" }
sdk = { path = "../sdk", version = "=1.9.29" }
storage-bigtable = { path = "../storage-bigtable", version = "=1.9.29" }
storage-proto = { path = "../storage-proto", version = "=1.9.29" }
vote-program = { path = "../programs/vote", version = "=1.9.29" }
tempfile = "3.2.0"
thiserror = "1.0"
tokio = { version = "~1.14.1", features = ["full"] }
tokio-stream = "0.1"
trees = "0.4.2"
reed-solomon-erasure = { version = "5.0.1", features = ["simd-accel"] }
evm-state = { path = "../evm-utils/evm-state" }
parking_lot = "0.12.1"

[dependencies.rocksdb]
# Avoid the vendored bzip2 within rocksdb-sys that can cause linker conflicts
# when also using the bzip2 crate
# version = "0.16.0"
default-features = false
features = ["lz4"]
#git = "https://github.com/velas/rust-rocksdb"
version = "0.20.1"

[dev-dependencies]
assert_matches = "1.5.0"
matches = "0.1.9"
account-decoder = { path = "../account-decoder", version = "=1.9.29" }

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "ledger"

#[[bench]]
#name = "sigverify_shreds"

#[[bench]]
#name = "blockstore"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
