[package]
name = "evm-bridge"
version = "0.1.0"
authors = ["Dean"]
edition = "2018"

[dependencies]
evm-rpc = { path = "../evm-rpc" }
sdk = { path = "../../sdk", version = "1.9.13" }
client = { path = "../../client", version = "1.9.29" }
cli-config = { path = "../../cli-config", version = "1.9.13" }
runtime = { path = "../../runtime", version = "1.9.29" }
transaction-status = { path = "../../transaction-status", version = "1.9.29" }
account-decoder = { path = "../../account-decoder", version = "1.9.13" }
logger = { path = "../../logger", version = "1.9.13" }
evm-loader-program = { path = "../programs/evm_loader" }
version = { path = "../../version" }
structopt = { version = "0.3", features = ["paw"] }
serde = "1.0.122"
serde_json = "1.0.60"
env_logger = "0.8.2"
paw = "1.0"
rlp = "0.5"
sha3 = "0.9.1"
bincode = "1.3"
borsh = "0.9.3"
hex = "0.4.2"
primitive-types = "0.11.0"
secp256k1 = { version = "0.19.0", features = ["recovery", "global-context"] }
evm-state = { path = "../evm-state" }
log = "0.4.11"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
jsonrpc-ws-server = "18.0.0"
rpc = { path = "../../rpc", version = "1.9.13" }
snafu = "0.7"
anyhow = "1.0"
tokio = "1"
txpool = { path = "../../txpool", version = "1.0.0-alpha" }
regex = "1.5.4"
reqwest = { version = "0.11.10", default-features = false, features = ["blocking", "rustls-tls", "json"] }
once_cell = "1"
derivative = "2.2"
base64 = "0.13"
semver = "1.0"

tracing = "0.1.29"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "smallvec",
    "fmt",
    "ansi",
    "std",
] }
tracing-attributes = "0.1.18"
tracing-opentelemetry  =  "0.16"
opentelemetry = { version = "0.16", default-features = false, features = ["trace"] }
opentelemetry-jaeger = { version = "0.15", features = [ "reqwest_collector_client", "rt-tokio" ] }

[features]
default=[]