[package]
name = "solana-send-transaction-service"
version = "1.9.29"
description = "Solana send transaction service"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-send-transaction-service"
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4.14"
solana-logger = { path = "../logger", version = "=1.9.29" }
solana-metrics = { path = "../metrics", version = "=1.9.29" }
solana-runtime = { path = "../runtime", version = "=1.9.29" }
solana-sdk = { path = "../sdk", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
